
name: Generate blog post pages

on:
  workflow_dispatch:

jobs:
  generate-posts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate pages
        run: node scripts/generate-posts.js

